In [1]:
import numpy as np

In [2]:
# Create an array from Python lists using np.array

In [3]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [4]:
# !Remember!: NumPy-Array only stores the same_type (int, string, float etc.) values unlike Lists that store multiple types.

In [5]:
# NumPy-array will try its best to Type-Cast if the values look different. Example:
np.array([ 3.14, 2, 4, 6])

array([3.14, 2.  , 4.  , 6.  ])

In [6]:
# ^ All the values are type casted to floating points.

In [7]:
# We can also explicitly set the data type

In [8]:
np.array([ 3.14, 5.6, 6], dtype='float32')

array([3.14, 5.6 , 6.  ], dtype=float32)

In [9]:
#
#
#
#

In [10]:
# NumPy-Array can be multi-dimensional unlike the single-dimension lists

In [19]:
# nested lists result in multi-dimensional arrays
np.array([range(i, i + 4) for i in [2, 4, 6, 8]])

array([[ 2,  3,  4,  5],
       [ 4,  5,  6,  7],
       [ 6,  7,  8,  9],
       [ 8,  9, 10, 11]])

In [20]:
#
#
#
#

In [21]:
# Creating arrays from scratch

# Zeros-NpArray
np.zeros(10, dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
# Create a 3x5 array of 1s integer

np.ones((3,5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [23]:
# Create a 4x8 array filled with 12s integer

np.full((4,8), 12, dtype='int')

array([[12, 12, 12, 12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12, 12, 12, 12]])

In [28]:
# Creating an array of a particular range (arange) and interval
# np.arange(Starting_Number, Ending_Number, Interval) : np.arange(0, 20, 5)

np.arange(0, 20, 5)

array([ 0,  5, 10, 15])

In [29]:
# Create an array from A to B but evenly sliced (linspace) by C values
# np.linspace(Starting_A, Ending_B, Slices_C) : np.linspace(0, 1, 5)

np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [30]:
# Create a random MxN array between 0-and-1 --> use np.random.random((N,M))

np.random.random((4,5))


array([[0.87672044, 0.7976531 , 0.18067533, 0.0976385 , 0.71919344],
       [0.1834579 , 0.00478138, 0.61944793, 0.68377879, 0.55744598],
       [0.23928472, 0.86961193, 0.17444285, 0.05617751, 0.92206057],
       [0.35655258, 0.57272452, 0.28697781, 0.40395129, 0.94613644]])

In [31]:
# Create an array with nomrally-distributed (random.normal) values of MxN size, with a mean and standard-deviation
# Example: np.random.normal(Mean, Standard-deviation, (M,N))

np.random.normal(0, 4, (5, 6))

array([[  1.36512654,  -8.36393248,   4.10392538,  -0.48690609,
         -1.04430453,  -0.58772769],
       [  1.30575159,   2.70990887,  -1.20251652,   5.7515748 ,
         -1.81423796,  -3.32484677],
       [  4.95966389,  -5.66309653,   2.74687809,   3.86851814,
         -1.53694071,   4.97751375],
       [  6.13147238,   0.15066523,  12.7349281 ,   4.10501238,
         -5.52240784,   4.68199554],
       [ -3.96582645, -11.4795281 ,   2.25357048,   1.09151501,
          1.04185393,  -5.2224603 ]])

In [33]:
# Create a MxN array of random integers (random.randint) between Minimum_Number_A to Maximum_Number_B
# np.random.randint(Minimum_number_A, Maximum_number_b, (M, N))

np.random.randint(5, 15, (4,3))

array([[10,  7,  6],
       [10, 14,  6],
       [ 6,  9, 12],
       [10,  9, 12]])

In [34]:
# Create an i(eye)dentity matrix of size MxM
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [36]:
# Create an un-initialized (empty) array of M integers
# Values will be given at run-time from what exists in the memory

np.empty(5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])