In [2]:
import numpy as np

In [4]:
# Use seed. Seed is used to make sure that the same random values are generated no matter where this code is ran

np.random.seed(0)

In [18]:
# Generate random arrays (seed enabled) of size 1D, 2D, and 3D.
# np.random.randint(Maximum_number, size=Dimensions)

x1 = np.random.randint(10, size = (6))
x2 = np.random.randint(10, size = (3, 4))
x3 = np.random.randint(10, size = (3, 4, 5) )

In [ ]:
# Each array has the 3 following attributes:
# 1. Number of dimensions (is it 2D or 1D or 3D): ndim
# 2. Size of each dimension (Example a 2D array can have the shape 4x5): shape
# 3. Total size of the array (Example a 2D array with the shape 4x5, can have the size 20): size

In [19]:
# Printing the ndim, shape, and size of x3:
print("The number of dimensions of x3 are", x3.ndim)
print("The shape of x3 is: ", x3.shape)
print("The size of x3 is: ", x3.size)

The number of dimensions of x3 are 3
The shape of x3 is:  (3, 4, 5)
The size of x3 is:  60


In [20]:
# Printing data-type of the array use: dtype

print("Data type of x3 is: ", x3.dtype)

Data type of x3 is:  int64


In [22]:
# Techniques to check the size:
# Individual size -> 'itemsize'
# Total size -> 'nbytes'

print("The size of each element of the x3 is: ", x3.itemsize)
print("The size of the entire array of x3 in bytes is: ", x3.nbytes)

The size of each element of the x3 is:  8
The size of the entire array of x3 in bytes is:  480


In [31]:
# Accessing elements of an array:
x1

array([1, 1, 2, 1, 4, 2])

In [35]:
x1[0:6]

array([1, 1, 2, 1, 4, 2])

In [36]:
x1[-2]

4

In [37]:
x2

array([[5, 5, 5, 2],
       [5, 7, 7, 6],
       [1, 6, 7, 2]])

In [39]:
x2[2,0]

1

In [40]:
x2[2,1]

6

In [41]:
x2[1,3]

6

In [42]:
x2[0,1] = 6

In [43]:
x2[0,2] = 7

In [44]:
x2[0, 3] = 8

In [45]:
x2

array([[5, 6, 7, 8],
       [5, 7, 7, 6],
       [1, 6, 7, 2]])

In [47]:
x2[1,1] = 11.56

In [48]:
x2

array([[ 5,  6,  7,  8],
       [ 5, 11,  7,  6],
       [ 1,  6,  7,  2]])

In [49]:
#
#
#

In [52]:
# Accessing subarrays using X[start:Stop:Step] --- Default -> Start=0, Stop=size, Step=1
x1[0:4:2]

array([1, 2])

In [53]:
# New 1D NP array

In [54]:
X = np.arange(10)

In [55]:
X

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
X[:5]

array([0, 1, 2, 3, 4])

In [58]:
X[5:]

array([5, 6, 7, 8, 9])

In [59]:
X[4:7]

array([4, 5, 6])

In [60]:
# Remember X[Start:Stop:Step]
X[::2]

array([0, 2, 4, 6, 8])

In [61]:
X[1::2]

array([1, 3, 5, 7, 9])

In [62]:
# Note negative step values just reverses the arrays
# X[State : Stop : Negative_Step] <- Reverses the arrays

X[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [63]:
X[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
X[9:1:-2]

array([9, 7, 5, 3])

In [67]:
X[:5:-1]

array([9, 8, 7, 6])

In [68]:
x2

array([[ 5,  6,  7,  8],
       [ 5, 11,  7,  6],
       [ 1,  6,  7,  2]])

In [77]:
x2[0:3,1:4]

array([[ 6,  7,  8],
       [11,  7,  6],
       [ 6,  7,  2]])

In [81]:
x2[:3,:2]

array([[ 5,  6],
       [ 5, 11],
       [ 1,  6]])

In [86]:
x2[0,:]

array([5, 6, 7, 8])

In [87]:
# First row of x2
print(x2[0])

[5 6 7 8]


In [90]:
# Reversing a 2D array

x2[::-2]

array([[1, 6, 7, 2],
       [5, 6, 7, 8]])

In [89]:
x2

array([[ 5,  6,  7,  8],
       [ 5, 11,  7,  6],
       [ 1,  6,  7,  2]])

In [91]:
x2[::-1, ::-1]

array([[ 2,  7,  6,  1],
       [ 6,  7, 11,  5],
       [ 8,  7,  6,  5]])

In [92]:
# '=' (Equaling) an array to a variable only stores a view and not a copy. See the examples below to understand:
# A
x2

array([[ 5,  6,  7,  8],
       [ 5, 11,  7,  6],
       [ 1,  6,  7,  2]])

In [93]:
# B
x2_copy = x2[0:2, 0:2]

In [94]:
# C
x2_copy

array([[ 5,  6],
       [ 5, 11]])

In [95]:
# D
x2_copy[ 0,0 ] = 99

In [96]:
# E
x2_copy

array([[99,  6],
       [ 5, 11]])

In [98]:
# F [Here, the x2[0,0] original array would have also changed to 99]
x2

array([[99,  6,  7,  8],
       [ 5, 11,  7,  6],
       [ 1,  6,  7,  2]])

In [99]:
# Lets use the .copy() function:

x2_copied = x2[0:2, 0:2].copy()

In [100]:
x2_copied

array([[99,  6],
       [ 5, 11]])

In [101]:
x2_copied[0,0] = 100

In [102]:
x2_copied

array([[100,   6],
       [  5,  11]])

In [103]:
x2

array([[99,  6,  7,  8],
       [ 5, 11,  7,  6],
       [ 1,  6,  7,  2]])

In [111]:
# Reshaping method helps in forming a specific shaped array

grid_array = np.arange( 0,9).reshape((3,3))

In [112]:
grid_array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [113]:
#
#
#

In [114]:
a = np.array([1, 2, 3])

In [115]:
a

array([1, 2, 3])

In [139]:
a.reshape(3,1)

array([[1],
       [2],
       [3]])

In [117]:
a

array([1, 2, 3])

In [118]:
# Uses of axis.
# Remember when axis = 0 it means chopping a log vertically
# and when axis = 1 it means chopping a log horizonatally

matrix = np.random.randint(1,11, 9).reshape(3,3)

In [119]:
matrix

array([[8, 3, 8],
       [2, 7, 6],
       [1, 1, 4]])

In [120]:
# Sum of matrix
matrix.sum()

40

In [122]:
# Sum of matrix's colums
matrix.sum(axis=0)

array([11, 11, 18])

In [124]:
# Sum of matrix's rows:
matrix.sum(axis = 1)

array([19, 15,  6])

In [129]:
# Find min and max of matrix
print(" Min of matrix : ", matrix.min())
print(" Max of matrix : ", matrix.max())

 Min of matrix :  1
 Max of matrix :  8


In [130]:
# FInd min and max of matrix per column
print(" Min of matrix per column : ", matrix.min(axis=0))

 Min of matrix per column :  [1 1 4]


In [131]:
# FInd min and max of matrix per row
print(" Min of matrix per row : ", matrix.min(axis=1))

 Min of matrix per row :  [3 2 1]


In [132]:
# Cumilative sum
matrix.cumsum()

array([ 8, 11, 19, 21, 28, 34, 35, 36, 40])

In [136]:
# Cumilative sum of matrix per row
print(" Cumilative sum of matrix per row: ", matrix.cumsum(axis=1))

 Cumilative sum of matrix per row:  [[ 8 11 19]
 [ 2  9 15]
 [ 1  2  6]]


In [137]:
# Cumilative sum of matrix per column
print("Cumilative sum of matrix per column: ", matrix.cumsum(axis=0))

Cumilative sum of matrix per column:  [[ 8  3  8]
 [10 10 14]
 [11 11 18]]


In [138]:
matrix

array([[8, 3, 8],
       [2, 7, 6],
       [1, 1, 4]])

In [145]:
# We can use np.concatenate to join arrays:
A = np.array([1, 2, 3])
B = np.array([8,9,10])
print(A, B)
C = np.concatenate([A, B])
print(C)

[1 2 3] [ 8  9 10]
[ 1  2  3  8  9 10]


In [147]:
# Concatenate another
D = np.array([11,12,13])
E = np.concatenate([A, B, D])
E

array([ 1,  2,  3,  8,  9, 10, 11, 12, 13])

In [148]:
# Concatenate 2D array

grid_A = ([1, 2, 3], [10, 20, 30])
grid_B = ([11, 12, 13], [21, 22, 23])
print(grid_A, grid_B)

([1, 2, 3], [10, 20, 30]) ([11, 12, 13], [21, 22, 23])


In [151]:
grid_AB_standard = np.concatenate([grid_A, grid_B])

In [152]:
grid_AB_standard

array([[ 1,  2,  3],
       [10, 20, 30],
       [11, 12, 13],
       [21, 22, 23]])

In [154]:
grid_AB_row_style = np.concatenate([grid_A, grid_B], axis=1)
grid_AB_row_style

array([[ 1,  2,  3, 11, 12, 13],
       [10, 20, 30, 21, 22, 23]])

In [155]:
# Now concatenate on column level (standard)
grid_AB_col_style = np.concatenate([grid_A, grid_B], axis=0)
print(grid_AB_col_style)

[[ 1  2  3]
 [10 20 30]
 [11 12 13]
 [21 22 23]]


In [161]:
# When the matrix are of different sizes then it is safe to us np.vstack and np.hstack
AA = np.array([[9, 8, 7], [6, 5, 4]])
AB = np.array([[20], [21]])
print(AA)
print(AB)

[[9 8 7]
 [6 5 4]]
[[20]
 [21]]


In [165]:
# Let's join them^ horizontally
AC = np.hstack([AA, AB])
AC

array([[ 9,  8,  7, 20],
       [ 6,  5,  4, 21]])

In [168]:
# Lets see vstack for vertical-stacking of same columns but different rows:
BB = np.array([[40, 41, 42],[50, 51, 52]])
BC = np.array([10, 11, 12])
print(BB)
print(BC)

[[40 41 42]
 [50 51 52]]
[10 11 12]
[[40 41 42]
 [50 51 52]
 [10 11 12]]


In [169]:
BA = np.vstack([BB, BC])
print(BA)

[[40 41 42]
 [50 51 52]
 [10 11 12]]


In [170]:
# The opposite of concatenation is splitting
# np.split | np.hsplit | np.vsplit

In [176]:
# Example of np.split:

X_X = np.array([10, 20, 30, 100, 200, 300, 1000, 2000, 3000])
print("X_X is: ", X_X)

X1, X2, X3 = np.split(X_X, [3, 7])
print(X1)
print(X2)
print(X3)

X_X is:  [  10   20   30  100  200  300 1000 2000 3000]
[10 20 30]
[ 100  200  300 1000]
[2000 3000]


In [180]:
# H-split and V-split are similar:

# V_split
V_V = np.arange(0,16).reshape(4,4)
V_V

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [181]:
V_up, V_low = np.vsplit(V_V, [2])

In [182]:
V_up

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [183]:
V_low

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [184]:
# H-Split
H_H = np.arange(1,31).reshape(5,6)
H_H

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [187]:
H_half1, H_half2 = np.hsplit(H_H, [3])

In [188]:
H_half1

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [13, 14, 15],
       [19, 20, 21],
       [25, 26, 27]])

In [189]:
H_half2

array([[ 4,  5,  6],
       [10, 11, 12],
       [16, 17, 18],
       [22, 23, 24],
       [28, 29, 30]])