In [8]:
# A basic inverse function

import numpy as np

def inverse_func(value):
    i = len(value)
    Ret_obj = np.empty(i)
    
    for objects in range(i):
        Ret_obj[objects] = 1.0/(value[objects])
    
    return Ret_obj

random_obj = np.random.randint(1, 20,size= 5)

inverse_func(random_obj)
    

array([1.        , 0.33333333, 0.14285714, 1.        , 0.06666667])

In [9]:
# ---

In [19]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit inverse_func(big_array)

2.16 s ± 61.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [20]:
%timeit (1.0/big_array)

1.83 ms ± 42.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [21]:
5//2

2

In [22]:
# Universal functions: These functions are optimized to perform vectorized operations.
# This saves a lot of time, and is good practice to follow.
# Examples:

x = np.array([-1 , -2, 4, 5])
x

array([-1, -2,  4,  5])

In [23]:
print("X in absolute: ", np.abs(x))

X in absolute:  [1 2 4 5]


In [25]:
y = np.array([3 - 4j, 5 - 6j, 0 + 1j, 3 + 0j])

In [26]:
np.abs(y)

array([5.        , 7.81024968, 1.        , 3.        ])

In [27]:
np.pi

3.141592653589793

In [32]:
Angle = np.linspace(0, np.pi, 3) # np.linspace(Start, End, Steps)
Angle

array([0.        , 1.57079633, 3.14159265])

In [36]:
print("Angle = ", Angle)
print("Angle-Sin =", np.sin(Angle))
print("Angle-Cos =", np.cos(Angle))
print("Angle-tan =", np.tan(Angle))

Angle =  [0.         1.57079633 3.14159265]
Angle-Sin = [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Angle-Cos = [ 1.000000e+00  6.123234e-17 -1.000000e+00]
Angle-tan = [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [41]:
# Inverse trig functions:
x = np.array([-1, 0, 1])
print("Inverse Arc-Sin = ", np.arcsin(x))
print("Inverse Arc-cos = ", np.arccos(x))
print("Inverse Arc-tan = ", np.arctan(x))

Inverse Arc-Sin =  [-1.57079633  0.          1.57079633]
Inverse Arc-cos =  [3.14159265 1.57079633 0.        ]
Inverse Arc-tan =  [-0.78539816  0.          0.78539816]


In [48]:
# Exponentials:
x = np.array([1, 2, 3])
print("X is = ", x)
print("e^x = ", np.exp(x))
print("2^x = ", np.exp2(x))
print("4^x = ", np.power(4, x))

X is =  [1 2 3]
e^x =  [ 2.71828183  7.3890561  20.08553692]
2^x =  [2. 4. 8.]
4^x =  [ 4 16 64]


In [52]:
# Log functions in np
x = np.array([1, 2, 3, 4])
print("X is    = ", x)
print("Log-X   = ", np.log(x))
print("Log2-x  = ", np.log2(x))
print("Log10-x = ", np.log10(x))

X is    =  [1 2 3 4]
Log-X   =  [0.         0.69314718 1.09861229 1.38629436]
Log2-x  =  [0.        1.        1.5849625 2.       ]
Log10-x =  [0.         0.30103    0.47712125 0.60205999]


In [55]:
# We could also use scipy (Science-Python) functions

from scipy import special as sp
x = np.array([1, 2, 3, 4])
print(" gamma(x) = ", sp.gamma(x))

 gamma(x) =  [1. 1. 2. 6.]


In [56]:
import scipy.special as special

In [61]:
# Saving calculation operation on a matrix into another empty matrix using out
x = np.arange(5)
y = np.empty(5)
np.add(x, 5, out=y)
y

array([5., 6., 7., 8., 9.])

In [64]:
# we can also space out how to save the values in a bigger array
x = np.arange(5)
y = np.empty(10)
np.power(2, x, out=y[::2])
y

array([ 1.,  0.,  2.,  0.,  4.,  0.,  8.,  0., 16.,  0.])

In [65]:
# Using reduce keyword to find a single ultimate answer in the arrays

x = np.arange(1,6)
x

array([1, 2, 3, 4, 5])

In [66]:
y = np.add.reduce(x)

In [67]:
y

15

In [68]:
y = np.multiply.reduce(x)
y

120

In [69]:
# Use accumulate to notice the addition or multiplication operations on each step

y = np.add.accumulate(x)

In [70]:
y

array([ 1,  3,  6, 10, 15])

In [71]:
y = np.subtract.accumulate(x)
y

array([  1,  -1,  -4,  -8, -13])