In [1]:
import pandas as pd
import numpy as np

In [6]:
rng = np.random.RandomState(42)
A_ser = rng.randint(0,10, 4)
A_ser

array([6, 3, 7, 4])

In [7]:
ser = pd.Series(A_ser)

In [8]:
ser

0    6
1    3
2    7
3    4
dtype: int64

In [10]:
df = pd.DataFrame(
    rng.randint(0, 10, (3,4)),
    columns = ['A', 'B', 'C', 'D']
)

df

A  B  C  D
0  1  7  5  1
1  4  0  9  5
2  8  0  9  2

In [11]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [12]:
area = pd.Series({'Alaska': 1723337,
                  'Texas': 695662,
                  'California': 423967},
                 name='area')

population = pd.Series({'California': 38332521,
                        'Texas': 26448193,
                        'New York': 19651127},
                       name='population')



In [13]:
population/area

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

In [14]:
population | area

Alaska        False
California     True
New York       True
Texas          True
dtype: bool

In [16]:
population.index & area.index

Index(['California', 'Texas'], dtype='object')

In [17]:
A = pd.Series(
    [2, 4, 6],
    index = [0, 1, 2]
)

B = pd.Series(
    [1, 3, 5],
    index = [1, 2, 3]
)

A + B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [18]:
# fill_value can help in overcoming NaN operations
A.add(B, fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [19]:
A = pd.DataFrame(rng.randint(0, 20, (2, 2)),
                columns=list('AB'))

A

A   B
0  11  19
1   2   4

In [20]:
B = pd.DataFrame(rng.randint(0, 10, (3,3)),
                columns= ['A', 'B', 'C'])
B

A  B  C
0  2  6  4
1  8  6  1
2  3  8  1

In [21]:
A + B

A     B   C
0  13.0  25.0 NaN
1  10.0  10.0 NaN
2   NaN   NaN NaN

In [22]:
A.add(B, fill_value=0)

A     B    C
0  13.0  25.0  4.0
1  10.0  10.0  1.0
2   3.0   8.0  1.0

In [24]:
# Pandas operations on 1D and 2D:

A = rng.randint(10, size=(3,4))
A

array([[9, 8, 9, 4],
       [1, 3, 6, 7],
       [2, 0, 3, 1]])

In [25]:
B = A[0]
B

array([9, 8, 9, 4])

In [26]:
A - B

array([[ 0,  0,  0,  0],
       [-8, -5, -3,  3],
       [-7, -8, -6, -3]])

In [27]:
df = pd.DataFrame(A, columns=list('QRST'))
df - df.iloc[0]

Q  R  S  T
0  0  0  0  0
1 -8 -5 -3  3
2 -7 -8 -6 -3

In [28]:
d1 = df.iloc[0, ::2]
d1

Q    9
S    9
Name: 0, dtype: int64

In [29]:
df - d1

Q   R    S   T
0  0.0 NaN  0.0 NaN
1 -8.0 NaN -3.0 NaN
2 -7.0 NaN -6.0 NaN